# Generated by Django 5.0.6 on 2024-07-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
